package lecture_manager.message;

public enum Type {

    CONNECT,
    SIGNUP,
    SIGNIN,
    SEND_CODE_AND_RESULT,
    SEND_PROBLEMS,
    REQUEST_PROBLEMS,
    REQUEST_STUDENTS,
    REQUEST_CHECKLIST,
    SEND_STUDENTLIST,
    START_SERVER,
    STOP_SERVER
}